name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git autotools-dev automake autoconf libtool pkg-config zlib1g-dev libffi-dev libssl-dev

    - name: Install buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0 cython==0.29.33

    - name: Build AAB
      run: |
        buildozer android release

    - name: Upload AAB
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-output
        path: |
          bin/
          .buildozer/android/platform/build*/build.log
