name: Build AAB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        
    - name: Build with Buildozer
      uses: entrofi/buildozer-action@v1.0.1
      with:
        workdir: ./
        buildozer_version: master
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: package
        path: bin/*.aab
