name: Build AAB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Kivy Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android release
        repository_root: .
        workdir: .
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-aab
        path: .buildozer/android/platform/build-*/bin/*.aab
