name: Build AAB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        build-tools: '30.0.3'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip build-essential libssl-dev libffi-dev python3-dev
        
    - name: Install Python dependencies
      run: |
        pip install buildozer kivy cython
        
    - name: Build AAB
      run: |
        buildozer android release
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-aab
        path: bin/*.aab
