name: Build AAB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk build-essential libssl-dev libffi-dev python3-dev
        pip install buildozer kivy cython
        
    - name: Build AAB
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        buildozer android release
        
    - name: Upload AAB
      uses: actions/upload-artifact@v2
      with:
        name: app-aab
        path: bin/*.aab
